### PR TITLE
Feature/user list

### LINKED ISSUE #7: Ensure turns are passed between all members
## Feature Request

**Is your feature request related to a problem? Please describe.**
We need to ensure that every member can have a turn during turn mode

**Describe the solution you'd like**
Turns get shared equally between members

**Describe alternatives you've considered**
None for now

**Teachability, Documentation, Adoption, Migration Strategy**
There will be a better turn UI which shows users clearly it's their turn. Also a save button which differentiates saving from passing.

### LINKED ISSUE #8: Hard to know the members in the group during the play
## Feature Request
- User-list feature is needed

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

- Not really sure who is in the group and who's turn when playing

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

- Would like to make the user list visible when playing the game 

**Describe alternatives you've considered**

- render the user name list to the `TurnModePage.tsx` 
- add active status to the member when it's turn

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?
Screen Shot 2022-08-19 at 16 58 28

### PR DESCRIPTION
**Pull request by kimm950**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
closes https://github.com/aburd/beats-with-friends/issues/8
closes #7 

*Any change needs to be documented in issues so that people are aware of what's being developed. 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

`UI improvement, adding user list feature`

* **What is the current behavior?** (You can also link to an open issue here)
`there is no visible member list in the `TurnModePage``

* **What is the new behavior (if this is a feature change)?**
`render the user name list to the TurnModePage.tsx`
`add active status to the member when it's their turn`
`use error modal when there is no nextUser`
`display group name in the header (top-right)`
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

`Nope`

* **Other information**:

Screen Shot 2022-08-19 at 16 58 28
Screen Shot 2022-08-19 at 17 12 49

### CODE REVIEW

**Comment by aburd** [comment]
@kimm950 Thanks for this PR! I'm actually working on something somewhat similar. If it's OK, would you mind if I merged #10 with this one?

**Comment by kimm950** [comment]
@aburd sure!!

**Comment by aburd** [comment]
@kimm950 
I messed up this PR bad...somehow when I rebased it got rid of your commits, but I think if you squash merge this, you should get the commit anyway.

**Comment by aburd** [comment]
As for the PR itself, the way you did it made me rethink how it should be approached! I like your approach of just putting the group stuff on the bottom. So I changed the code to just keep all the "group stuff" in a GroupMenu component!

If you're happy with this, please go ahead and merge!

**Review by aburd — APPROVED** [review]

**Comment by aburd** [comment]
Screenshot from 2022-08-22 20-10-53
Screenshot from 2022-08-22 20-11-14

**Comment by aburd** [comment]
@kimm950 
Also, I wasn't really picky about the styling, so my code may have messed a bit with what you're trying to do (put the group styling in the sequencer). If you wanna change that back go for it!

I really liked what you did with the simple approach of making the active user orange so I definitely wanted to keep that.

**Comment by kimm950** [comment]
> I messed up this PR bad...somehow when I rebased it got rid of your commits, but I think if you squash merge this, you should get the commit anyway.

It's all good!

> If you're happy with this, please go ahead and merge!

I am happy, let me merge this!

**Pull request merged**
